

POST http://127.0.0.1:5000/
Content-Type: multipart/form-data

{
    "id": 3,
    "name": "Mani"
}

###

GET  http://127.0.0.1:5000/hello
Content-Type: multipart/form-data


# {
#     "id": 3,
#     "name": "Mani"
# }
