### CREATE a new Pydantic user
POST http://localhost:5000/api/pyduser
Content-Type: application/json

{
    "id": 1,
    "name": "Sample Pydantic",
    "email": "pydantic@gmail.com"
}

###

### READ all Pydantic users
GET http://localhost:5000/api/pyduser

###

### READ a single Pydantic user by ID
GET http://localhost:5000/api/pyduser/1

###

### CREATE a new Custom user
POST http://localhost:5000/api/customuser
Content-Type: application/json

{
    "id": 1,
    "name": "Custom User",
    "email": "custom@gmail.com"
}

###

### READ all Custom users
GET http://localhost:5000/api/customuser

###

### READ a single Custom user by ID
GET http://localhost:5000/api/customuser/1

###

### CREATE a new Dataclass user
POST http://localhost:5000/api/dcuser
Content-Type: application/json

{
    "id": 3,
    "name": "Dataclass User",
    "email": "dataclass@gmail.com"
}

###

### READ all Dataclass users
GET http://localhost:5000/api/dcuser

###

### READ a single Dataclass user by ID
GET http://localhost:5000/api/dcuser/3

###
